First_collevel = [
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '         c              c                  c                                      ',
        '                                                                                  ',
        '       c        c              c       c                    c          c          ',
        '                                                                                  ',
        '  c                                                  c                            ',
        '                                                                                  ',
        '                c                                                                 ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '         iii                   iiii               iii                             ',
        '     iii                                      iii                                 ',
        '  iii                                      iii                                    ',
        '               iiiii         iiiii                      iiiii                     ',
        ' i                                        i                                       ',
        '    i                                        i                                    ',
        '                     iiii                                     iiii                ',
        '                                   iiiiii                                   iiiiii',
        'ddd     d   ddd   d d ddddd dddd         ddd     d   ddd   d d ddddd dddd         ',
        'tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt']

First_Grlevel = [
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '         c              c                  c                                      ',
        '                                                                                  ',
        '       c        c              c       c                    c          c          ',
        '                                                                                  ',
        '  c                                                  c                            ',
        '                                                                                  ',
        '                c                                                                 ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        ' gg  g  gggg  g       ggg ggg     gg g g  gg  g  gggg  g       ggg ggg     gg g g ']

First_clue = [
        '                                                                                  ',
        '                                                                                  ',
        '                                          y                                       ',
        '       y                                                         y                ',
        '                                                                                  ',
        '                               y                                                  ',
        '                                                                                  ',
        '       y                                                                          ',
        '                                                                                  ',
        '                                                               y                  ',
        '               y                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                              y                                   ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                   y                                                              ',
        '                                      y                                           ',
        '                                                      y                           ',
        '                                                                                  ',
        '                       y                                                          ',
        '                                                                                  ',
        '                                                                    y             ',
        '                                                                                  ',
        '                                                                                  ',
        '          y                     y                        y                        ',
        '                                                                                  ',
        '                                                                                  ']

'''=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- SECOND LEVEL -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-='''

Second_collevel = [
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '         c              c                  c                                      ',
        '                                                                                  ',
        '       c        c              c       c                    c          c          ',
        '                                                                                  ',
        '  c                                                  c                            ',
        '                                                                                  ',
        '                c                                                                 ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '         iii                   iiii               iii                             ',
        '     iii                                      iii                                 ',
        '  iii                                      iii                                    ',
        '               iiiii         iiiii                      iiiii                     ',
        ' i                                        i                                       ',
        '  iii                                        i                                    ',
        '                     iiii                                     iiii                ',
        '                                   iiiiii                                   iiiiii',
        'ddddddddd   ddd   d d ddddd dddd         ddd     d   ddd   d d ddddd dddd         ',
        'tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt']

Second_Grlevel = [
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '         c              c                  c                                      ',
        '                                                                                  ',
        '       c        c              c       c                    c          c          ',
        '                                                                                  ',
        '  c                                                  c                            ',
        '                                                                                  ',
        '                c                                                                 ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        ' gg  g  gggg  g       ggg ggg     gg g g  gg  g  gggg  g       ggg ggg     gg g g ']

Second_clue = [
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                 y                                                                ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                 y                ',
        '                                                                                  ',
        '                                                                                  ',
        '                                              y                                   ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '      y                                                                           ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                 y                                ',
        '                                                                                  ',
        '          y          y                                                            ',
        '                                                                                  ',
        '                                                                                  ',
        '     y                                                                            ',
        '                                                                                  ',
        '                                                                                  ',
        '                                                                                  ']

Therd_collevel = [
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ',
        '     ']
